version: "3.7"

services:
  # Application
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    links:
      - mongo
    ports:
      - 7000:7000
    links:
      - postgres

  # Database image
  postgres:
    container_name: backstage_db
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

networks:
  default:
    external:
      name: madeiramadeira